name = "approval-hub"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "approval-hub"
route = "approval-hub.your-domain.com/*"

[env.staging]
name = "approval-hub-staging"
route = "staging-approval-hub.your-domain.com/*"

# Environment variables (set these in Cloudflare dashboard)
# GITHUB_TOKEN = "your_github_personal_access_token"

# Functions configuration
[functions]
directory = "functions" 